### PR TITLE
Fixed AE Bug

### PR DESCRIPTION
**Pull request by DrummerMC**

### CODE REVIEW

**Comment by TheJulianJES** [comment]
Looks good to me! I will now compile it for myself, I will post my results here!

**Comment by DrummerMC** [comment]
I have test it with rv1 stable and it works

**Comment by Korynkai** [comment]
Be very careful with this pull request being RV2, his code may currently run on RV2 (I haven't tested it yet, I can confirm his old pull request runs perfectly on RV1 as we're using it on our stable server), but the API he's using now was updated about a month ago whereas the ABI was updated only two days ago. If you follow the changes closely you realize alot of identifiers in the ABI have changed in this time and they're bound to update the API to resemble these changes. I suggest watchful waiting (as was prescribed directly from the AE2 devs anyway, courtesy the author of the warning on http://ae-mod.info/#rv2_alpha ) and pulling his commit b2e0f15dcc in the meantime to fix AE2 RV1.

Edit: Huh, I stand corrected, the specific line I was referring to was not changed. However it's still safe to assume that the RV2 API is highly unstable (and may change) so proceed with caution.

**Comment by DrummerMC** [comment]
I have testet it on rv1 stable 1 and on rv2 alpha 19 and it works
It works on both

**Comment by Korynkai** [comment]
Yes, but I'm telling him to proceed with caution due to the current changing nature of RV2, not whether or not it works right now. He may simply want to include the RV1 fix at this point rather than support both, but this is up to him.

**Comment by DrummerMC** [comment]
He can include both and write:"in you use it on rv2 Do it on your own risik."

**Comment by DrummerMC** [comment]
Closed
Please use: https://github.com/Eximius88/ModularPowersuitsAddons/pull/22

**Pull request closed without merging**
